### ISSUE TITLE
useRadio inputProps reference HTMLInput, not react native

### ISSUE THREAD

**Issue by davidpett** [gluestack/react-native-aria#10]
While implementing useRadio(), I am getting a typescript error with mismatching props on the <Pressable/> component because `inputProps` is referencing the HTMLInput https://github.com/gluestack/react-native-aria/blob/9e4d342767277ae32c30b96fe17cc2e1b6be2ec7/packages/radio/src/useRadio.ts#L22 and not the native props (or `any` like useCheckbox() does)

The types should probably reference React Native component props instead of HTML as react-native-web will handle that translation

**Comment by surajahmed** [comment]
Thanks for reporting this @davidpett. We'll update this as soon as possible.

**Comment by makkarMeenu** [comment]
Hey @davidpett , apologies for not attending your query. I have changed to type to any like Checkbox does for now and released a new version for checkbox and radio.
