### ISSUE TITLE
In React Native, the Slider can't be dragged, it can only be clicked.

### ISSUE THREAD

**Issue by taixw2** [gluestack/react-native-aria#16]
<img src="https://github.com/gluestack/react-native-aria/assets/12482817/13b7c1a7-05d3-4380-8b56-ece85ac1769c" alt="https://github.com/gluestack/react-native-aria/assets/12482817/13b7c1a7-05d3-4380-8b56-ece85ac1769c" width=
"30%" />

### Expectation
Slider can be dragged and moved

**Comment by Gluant101** [comment]
Hey @taixw2, really sorry for the delay. We'll look into this.

**Comment by makkarMeenu** [comment]
This is fixed in the latest version, please check.
